#!/bin/bash

DIR_CONFIG=$HOME/dotfiles

echo "Configuration to Setup - Profile"

if [ -f "$HOME/.profile" ]
then
    FILE_PROFILE=$HOME/.profile
elif [ -f "$HOME/.bash_profile" ]
then
    FILE_PROFILE=$HOME/.bash_profile
fi

if [ -f "$FILE_PROFILE" ]
then
    echo ". $DIR_CONFIG/profile" >> $FILE_PROFILE
    echo "OK"
else
    echo "Profile not found"
fi

echo "Configuration to Setup - Profile"

if [ -f "$HOME/.bashrc" ]
then
    FILE_BASHRC=$HOME/.bashrc
fi

if [ -f "$FILE_BASHRC" ]
then
    echo ". $DIR_CONFIG/bashrc" >> $FILE_BASHRC
    echo "OK"
else
    echo "Bashrc not found"
fi

echo "Configuration VIM"

cp $DIR_CONFIG/vim/.vimrc $HOME/.
cp $DIR_CONFIG/vim/vundles.vim $HOME/.vim

echo "Configuration GIT"

cp $DIR_CONFIG/git/.gitconfig $HOME/.
echo "OK"

echo "Done"
